### ISSUE TITLE
Custom input element dont accecpt display format vue 3 or vue2

### ISSUE THREAD

**Issue by AMSANJI-WORK** [talkhabi/vue3-persian-datetime-picker#3]
when we use custom input the display format property not working

**Comment by mssayari** [comment]
I have the same problem. I would like to use **Gregorian** but display **Jalali** while I'm using custom input.

**Comment by talkhabi** [comment]
Ok, currently it is not supported, but I will try to add it.
https://talkhabi.github.io/vue-persian-datetime-picker/guide/custom-input.html
